server:
  port: 9001
spring:
  thymeleaf:
    cache: false
security:
  oauth2:
    client:
      client-id: client1
      client-secret: mengxuegu-secret
      user-authorization-uri: http://localhost:8090/auth/oauth/authorize # 请求认证的地址
      access-token-uri: http://localhost:8090/auth/oauth/token # 获取令牌地址
    resource:
      jwt:
          # 当用户授权后会带着授权码重定向到客户端http://localhost:9001/login?code=xxxx
          # 对应/login会自动的去获取令牌，并通过key-uri指定地址去获取公钥校验令牌有效性
          # 然后完成本次认证与授权
        key-uri: http://localhost:8090/auth/oauth/token_key